add_rules("mode.debug", "mode.release")

target("sample_dls")
    set_kind("static")
    add_includedirs("include", {public = true})
    add_files("src/dhv.cpp")
    add_includedirs("net", {public = true})
    add_files("net/*.cpp")
    add_files("src/*.cpp")
    add_files("lib/nng/*.a")
    add_files("lib/hv/*.a")
    add_linkdirs("lib/nng")
    add_links("nng")
    add_linkdirs("lib")
    add_links("sample_nng")
    add_links("z")
    add_links("glog")
    add_links("media_mpp")
    add_links("mpp_component")
    add_links("media_utils")
    add_links("expat")
    add_links("sample_confparser")
    add_links("mpp_vi")
    add_links("mpp_isp")
    add_links("ISP")
    add_links("mpp_vo")
    add_links("cdc_base")
    add_links("adecoder")
    add_links("unwind")
    add_links("cdx_common")
    add_links("asound")
    add_links("cedarx_tencoder")
    add_links("MemAdapter")
    add_links("VE")
    add_links("vencoder")
    add_links("venc_base")
    add_links("venc_common")
    add_links("vdecoder")
    add_links("cedarx_aencoder")
    add_links("cdx_parser")
    add_links("cdx_stream")
    add_links("Resample")
    add_links("cedarxstream")
    add_links("isp_ini")
    add_links("cdx_base")
    add_links("cedarxrender")
    add_links("videoengine")
